version: '2'

services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
  wordpress:
    #image: bitnami/wordpress:latest
    #image: bitnami/wordpress:4.6.1-r7
    build: .
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - wordpress_data:/bitnami/wordpress
      - apache_data:/bitnami/apache
      - php_data:/bitnami/php

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local