# Usage:
# docker-compose build && docker-compose up
# docker-compose exec wordpress wp-monei-setup
version: '2'

services:
  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
  wordpress:
    build: .
    depends_on: 
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - '80:80'
      - '443:443'
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_PASSWORD: password
      MONEI_CHANNEL_ID: some_channel
      WORDPRESS_SITE_TITLE: some_site_title
      WORDPRESS_ADMIN_PASSWORD: 1234 

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local