# Usage:
# docker-compose build && docker-compose up
# docker-compose exec wordpress wp-monei-setup
version: '2'

services:
  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
  wordpress:
    build: .
    depends_on: 
      - mariadb
    links:
      - mariadb:mysql
    ports:
      - '80:80'
      - '443:443'
    environment:
      MONEI_OPERATION_MODE: live
      MONEI_TEST_CHANNEL_ID: test_channel_id
      MONEI_TEST_USER_ID: test_user_id
      MONEI_TEST_PASSWORD: test_password
      MONEI_LIVE_CHANNEL_ID: live_channel_id
      MONEI_LIVE_USER_ID: live_user_id
      MONEI_LIVE_PASSWORD: live_password
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_SITE_TITLE: some_site_title
      WORDPRESS_ADMIN_PASSWORD: 1234 

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local